contact_links:
  - name: ✨ Official BarbaJS website
    url: https://barba.js.org/
    about: New to BarbaJS? Have a look at the website before opening an issue.
  - name: 💬 Slack workspace
    url: https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTkxYWUwZmM1YWQxMmNlYmE0ZjY4NDQxMGUxYjkwYWFlMzEzOWM4OTRhMWRmYTQyYzFlMmQ3OGFmYmI3MWY0OWY
    about: Want to discuss or chat with the community? Join using the invite link!
